version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: megamax
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ../backend
    env_file:
      - ../backend/.env.example
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/megamax
    ports:
      - "4000:4000"
    depends_on:
      - db

  frontend:
    build:
      context: ../frontend
    env_file:
      - ../frontend/.env.example
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pgdata:
